/**
 * Barrel re-export from @ascend/core.
 *
 * All Zod schemas, enum schemas, and inferred types now live in the
 * platform-agnostic @ascend/core package. This file preserves the
 * existing import surface (`from "@/lib/validations"`) so that no
 * consumers need to be rewritten.
 */
export {
  // Enum schemas
  horizonEnum,
  statusEnum,
  priorityEnum,
  recurringFrequencyEnum,
  todoStatusEnum,
  // Goal schemas and types
  createGoalSchema,
  updateGoalSchema,
  goalFiltersSchema,
  addProgressSchema,
  reorderGoalsSchema,
  type CreateGoalInput,
  type UpdateGoalInput,
  type GoalFilters,
  type AddProgressInput,
  type ReorderGoalsInput,
  // Todo schemas and types
  createTodoSchema,
  updateTodoSchema,
  todoFiltersSchema,
  bulkCompleteTodosSchema,
  setBig3Schema,
  reorderTodosSchema,
  type CreateTodoInput,
  type UpdateTodoInput,
  type TodoFilters,
  type BulkCompleteTodosInput,
  type SetBig3Input,
  type ReorderTodosInput,
  // Category schemas and types
  createCategorySchema,
  updateCategorySchema,
  type CreateCategoryInput,
  type UpdateCategoryInput,
  // Context enum schemas
  contextEntryTypeSchema,
  contextLinkTypeSchema,
  contextLinkSourceSchema,
  contextSearchModeSchema,
  CONTEXT_SEARCH_MODE_VALUES,
  // Context schemas and types
  createContextSchema,
  updateContextSchema,
  contextFiltersSchema,
  contextSearchSchema,
  createContextLinkSchema,
  updateContextLinkSchema,
  deleteContextLinkQuerySchema,
  contextGraphFiltersSchema,
  contextNeighborsQuerySchema,
  type ContextSearchMode,
  type CreateContextInput,
  type UpdateContextInput,
  type ContextFilters,
  type CreateContextLinkInput,
  type UpdateContextLinkInput,
  type DeleteContextLinkQuery,
  type ContextGraphFilters,
  type ContextNeighborsQuery,
  // Auth schemas and types
  loginSchema,
  registerSchema,
  refreshSchema,
  type LoginInput,
  type RegisterInput,
  type RefreshInput,
  // Shared schemas and types
  dateQuerySchema,
  dateRangeQuerySchema,
  importDataSchema,
  type ImportData,
  type ImportCategoryEntry,
  type ImportGoalEntry,
  weeklyReviewQuerySchema,
  type WeeklyReviewQuery,
  saveReviewSchema,
  type SaveReviewInput,
  streakHistoryQuerySchema,
  type StreakHistoryQuery,
  analyticsQuerySchema,
  type AnalyticsQuery,
  createFocusSessionSchema,
  type CreateFocusSessionInput,
  focusSessionFiltersSchema,
  type FocusSessionFilters,
  // File schemas and types
  ALLOWED_MIME_TYPES_ARRAY,
  ALLOWED_MIME_TYPES,
  UPLOAD_MAX_BYTES,
  PRESIGN_EXPIRES_SECONDS,
  DOWNLOAD_URL_EXPIRES_SECONDS,
  EXTRACTION_STATUS_VALUES,
  presignUploadSchema,
  confirmUploadSchema,
  fileStatusSchema,
  reExtractSchema,
  uploadFileToolSchema,
  getFileContentToolSchema,
  listFilesByTypeToolSchema,
  type AllowedMimeType,
  type ExtractionStatusValue,
  type PresignUploadInput,
  type ConfirmUploadInput,
  type FileStatus,
  type ReExtractInput,
  type UploadFileToolInput,
  type GetFileContentToolInput,
  type ListFilesByTypeToolInput,
  // Block editor schemas and types
  serializedEditorStateSchema,
  syncBlockUpdateSchema,
  blockOpAddSchema,
  blockOpUpdateSchema,
  blockOpMoveSchema,
  blockDocumentSnapshotSchema,
  type SerializedEditorStateInput,
  type SyncBlockUpdateInput,
  type BlockOpAddInput,
  type BlockOpUpdateInput,
  type BlockOpMoveInput,
  type BlockDocumentSnapshot,
  // LLM schemas and types
  chatProviderKindSchema,
  usageWindowSchema,
  contextMapContentSchema,
  contextMapSchema,
  llmUsageSchema,
  updateAiSettingsSchema,
  llmChatRequestSchema,
  llmUsageQuerySchema,
  type ContextMapItem,
  type ContextMapContent,
  type ContextMap,
  type LlmUsage,
  type UpdateAiSettingsInput,
  type LlmChatRequestInput,
  type LlmUsageQuery,
  // Versioning schemas and types (Wave 7)
  NODE_TYPE_VALUES,
  nodeTypeEnum,
  VERSION_TRIGGER_VALUES,
  versionTriggerEnum,
  EDGE_EVENT_TYPE_VALUES,
  edgeEventTypeEnum,
  nodeVersionPayloadSchema,
  listVersionsQuerySchema,
  diffVersionsBodySchema,
  restoreVersionBodySchema,
  branchNodeBodySchema,
  graphAtQuerySchema,
  type NodeType,
  type VersionTrigger,
  type EdgeEventType,
  type ListVersionsQuery,
  type DiffVersionsBody,
  type RestoreVersionBody,
  type BranchNodeBody,
  type GraphAtQuery,
  // Database schemas and types
  DATABASE_FIELD_TYPE_VALUES,
  DATABASE_VIEW_TYPE_VALUES,
  databaseFieldTypeSchema,
  databaseViewTypeSchema,
  selectOptionSchema,
  databaseFieldConfigSchema,
  databaseFieldSchema,
  createDatabaseFieldSchema,
  updateDatabaseFieldSchema,
  textValueSchema,
  numberValueSchema,
  dateValueSchema,
  selectValueSchema,
  multiSelectValueSchema,
  relationValueSchema,
  formulaValueSchema,
  userValueSchema,
  checkboxValueSchema,
  ratingValueSchema,
  urlValueSchema,
  emailValueSchema,
  phoneValueSchema,
  fileValueSchema,
  getValueSchemaForType,
  databaseRowPropertiesSchema,
  FILTER_OP_VALUES,
  filterOpSchema,
  filterCombinatorSchema,
  filterSchema,
  sortItemSchema,
  sortSchema,
  databaseViewConfigSchema,
  createDatabaseSchema,
  updateDatabaseSchema,
  createDatabaseViewSchema,
  updateDatabaseViewSchema,
  createDatabaseRowSchema,
  updateDatabaseRowSchema,
  reorderDatabaseRowsSchema,
  reorderDatabaseFieldsSchema,
  databaseQuerySchema,
  type DatabaseFieldType,
  type DatabaseViewType,
  type SelectOption,
  type DatabaseFieldConfig,
  type DatabaseField,
  type CreateDatabaseFieldInput,
  type UpdateDatabaseFieldInput,
  type FilterOp,
  type FilterCombinator,
  type FilterFieldClause,
  type FilterSchema,
  type SortItem,
  type SortSchema,
  type DatabaseViewConfig,
  type CreateDatabaseInput,
  type UpdateDatabaseInput,
  type CreateDatabaseViewInput,
  type UpdateDatabaseViewInput,
  type CreateDatabaseRowInput,
  type UpdateDatabaseRowInput,
  type ReorderDatabaseRowsInput,
  type ReorderDatabaseFieldsInput,
  type DatabaseQueryInput,
  // Workspace schemas and types (Wave 8)
  WORKSPACE_ROLE_VALUES,
  workspaceRoleEnum,
  MEMBERSHIP_STATUS_VALUES,
  membershipStatusEnum,
  workspaceSchema,
  createWorkspaceSchema,
  updateWorkspaceSchema,
  workspaceMembershipSchema,
  type WorkspaceRole,
  type MembershipStatus,
  type Workspace,
  type CreateWorkspaceInput,
  type UpdateWorkspaceInput,
  type WorkspaceMembership,
  // Activity event schemas and types (Wave 8)
  ACTIVITY_EVENT_TYPE_VALUES,
  activityEventTypeEnum,
  workspaceCreatedPayloadSchema,
  memberAddedPayloadSchema,
  memberRemovedPayloadSchema,
  memberRoleChangedPayloadSchema,
  nodeCreatedPayloadSchema,
  nodeDeletedPayloadSchema,
  nodeRestoredPayloadSchema,
  nodeBranchedPayloadSchema,
  linkCreatedPayloadSchema,
  linkRemovedPayloadSchema,
  activityEventPayloadSchema,
  activityEventSchema,
  type ActivityEventType,
  type WorkspaceCreatedPayload,
  type MemberAddedPayload,
  type MemberRemovedPayload,
  type MemberRoleChangedPayload,
  type NodeCreatedPayload,
  type NodeDeletedPayload,
  type NodeRestoredPayload,
  type NodeBranchedPayload,
  type LinkCreatedPayload,
  type LinkRemovedPayload,
  type ActivityEventPayload,
  type ActivityEvent,
  activityFeedQuerySchema,
  type ActivityFeedQuery,
  // Permission schemas and types (Wave 8)
  PERMISSION_ACTION_VALUES,
  permissionActionEnum,
  type PermissionAction,
  // CRDT schemas and types (Wave 8 Phase 4)
  crdtTokenRequestSchema,
  crdtPersistBodySchema,
  type CrdtTokenRequestInput,
  type CrdtPersistBodyInput,
} from "@ascend/core";
