/**
 * Barrel re-export from @ascend/core.
 *
 * All Zod schemas, enum schemas, and inferred types now live in the
 * platform-agnostic @ascend/core package. This file preserves the
 * existing import surface (`from "@/lib/validations"`) so that no
 * consumers need to be rewritten.
 */
export {
  // Enum schemas
  horizonEnum,
  statusEnum,
  priorityEnum,
  recurringFrequencyEnum,
  todoStatusEnum,
  // Goal schemas and types
  createGoalSchema,
  updateGoalSchema,
  goalFiltersSchema,
  addProgressSchema,
  reorderGoalsSchema,
  type CreateGoalInput,
  type UpdateGoalInput,
  type GoalFilters,
  type AddProgressInput,
  type ReorderGoalsInput,
  // Todo schemas and types
  createTodoSchema,
  updateTodoSchema,
  todoFiltersSchema,
  bulkCompleteTodosSchema,
  setBig3Schema,
  reorderTodosSchema,
  type CreateTodoInput,
  type UpdateTodoInput,
  type TodoFilters,
  type BulkCompleteTodosInput,
  type SetBig3Input,
  type ReorderTodosInput,
  // Category schemas and types
  createCategorySchema,
  updateCategorySchema,
  type CreateCategoryInput,
  type UpdateCategoryInput,
  // Context enum schemas
  contextEntryTypeSchema,
  contextLinkTypeSchema,
  contextLinkSourceSchema,
  // Context schemas and types
  createContextSchema,
  updateContextSchema,
  contextFiltersSchema,
  contextSearchSchema,
  createContextLinkSchema,
  updateContextLinkSchema,
  deleteContextLinkQuerySchema,
  contextGraphFiltersSchema,
  contextNeighborsQuerySchema,
  type CreateContextInput,
  type UpdateContextInput,
  type ContextFilters,
  type CreateContextLinkInput,
  type UpdateContextLinkInput,
  type DeleteContextLinkQuery,
  type ContextGraphFilters,
  type ContextNeighborsQuery,
  // Auth schemas and types
  loginSchema,
  registerSchema,
  refreshSchema,
  type LoginInput,
  type RegisterInput,
  type RefreshInput,
  // Shared schemas and types
  dateQuerySchema,
  dateRangeQuerySchema,
  importDataSchema,
  type ImportData,
  type ImportCategoryEntry,
  type ImportGoalEntry,
  weeklyReviewQuerySchema,
  type WeeklyReviewQuery,
  saveReviewSchema,
  type SaveReviewInput,
  streakHistoryQuerySchema,
  type StreakHistoryQuery,
  analyticsQuerySchema,
  type AnalyticsQuery,
  createFocusSessionSchema,
  type CreateFocusSessionInput,
  focusSessionFiltersSchema,
  type FocusSessionFilters,
  // File schemas and types
  ALLOWED_MIME_TYPES_ARRAY,
  ALLOWED_MIME_TYPES,
  UPLOAD_MAX_BYTES,
  PRESIGN_EXPIRES_SECONDS,
  presignUploadSchema,
  confirmUploadSchema,
  type AllowedMimeType,
  type PresignUploadInput,
  type ConfirmUploadInput,
  // LLM schemas and types
  chatProviderKindSchema,
  usageWindowSchema,
  contextMapContentSchema,
  contextMapSchema,
  llmUsageSchema,
  updateAiSettingsSchema,
  llmUsageQuerySchema,
  type ContextMapItem,
  type ContextMapContent,
  type ContextMap,
  type LlmUsage,
  type UpdateAiSettingsInput,
  type LlmUsageQuery,
} from "@ascend/core";
